apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    run: my-nginx
spec:
  containers:
  - name: test-container
    image: nginx:1.25
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      value: postgres://db_url:5432